### ISSUE TITLE
Live Verdolmetschung der Vorträge organisieren

### ISSUE THREAD

**Issue by hgaertnerbr** [cogneon/loscon24#16]
Es wird einen englischen Track geben. Wir werden die Vorträge, ggfls. Lightning Talks etc. live verdolmetschen. Verdolmetschung Englisch-Deutsch, Deutsch-Englisch, je nach Ausgangssprache.

Ziele: Bereitstellung der Verdolmetschung für Fremdsprachige TN, Veröffentlichung der Vorträge auf Social Media Kanälen in zwei Sprachen (Deutsch- English)

- Wir brauchen ein Tool mit geringer Latenz
- Hinweise auf Verdolmetschung im Programm mit Anleitung

**Comment by simondueckert** [comment]
Dieses Jahr sollten wir auf jeden Fall Teams nochmal probieren, um die Komplexität zu reduzieren.

**Comment by hgaertnerbr** [comment]
Wir brauchen noch einen Testtermin mit Vorlauf, damit wir notfalls Alternativen testen können. Und selbst wenn Teams klappt müssen wir kurz vorher nochmal einen Test machen, ob es wirklich klappt. Am 2 Juli müssen die Dolmetscherinnen dann vor 13.00 Uhr in die Session reinkommen.

Dolmetscherinnen:
**Hilla Widemann**, Brüssel (info@hillawiedemann.de, https://www.linkedin.com/in/hilla-widemann-86982314/)
**Daniela Schell**, Bad Soden (info@danielaschell.de, http://www.danielaschell.de/dolmetscher/Daniela_Schell_-_Konferenzdolmetscher.html)

**Comment by simondueckert** [comment]
Machen wir dieses Jahr nicht. Nächstes Jahr eigenes Team mit dem Start der mehrsprachigen Leitfäden.
