### ISSUE TITLE
Drehbuch mit Rollenbeschreibungen erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#20]
Zu besetzen sind:
- Beide Tage
   - Master of Ceremony (MC, letztes Jahr Sandra, ist dieses Jahr remote)
   - Support Podcast-Tisch
- Tag 1
   - [ ] Koordination Infodesk/Empfang
   - [ ] Infodesk/Empfang 1
   - [ ] Infodesk/Empfang 2 (Stoßzeiten)
   - [ ] Room Buddy 1
   - [ ] Room Buddy 2
   - [ ] Room Buddy 3
   - [ ] Room Buddy 4
   - [ ] Moderation vor Ort
   - [ ] Moderation Remote
   - [ ] Fakelträger:in: Viktoria
- Tag 2
   - [ ] Koordination Infodesk/Empfang
   - [ ] Infodesk/Empfang 1
   - [ ] Infodesk/Empfang 2 (Stoßzeiten)
   - [ ] Room Buddy 1
   - [ ] Room Buddy 2
   - [ ] Room Buddy 3
   - [ ] Room Buddy 4
   - [ ] Moderation vor Ort
   - [ ] Moderation Remote
   - [ ] Abbauteam

Idee: Doppelbesetzung, so dass wir von Jahr zu Jahr Überlapp und damit Wissenstransfer haben.

# Rollenbeschreibungen und Aufgaben
tbd.

**Comment by Sandra-Richter** [comment]
Ich übernehme gern Moderation Remote an Tag 2 und kümmere mich an Tag 2 auch darum, dass die Onliner:innen sich betreut fühlen und beantworte Fragen etc. in Discord etc.

**Comment by simondueckert** [comment]
- Sabrina: online auf jeden Fall, aber dienstliche Termine
- Christian: 2./3. da (übernachtet Nürnberg)
- Manuel: 2./3. da, kann am 1. aufbauen
- Sandra: online, 2. bis 14:30, 3. komplett
- Hans: komplett da, auch 1.
- Anke: 2./3. vor Ort
- Martin: 1./2. Deadline 1530-1600, am 3. nicht
- Nicole: Online
- Marcel: 1.-3. (mit Stefan und Ruben)

ToDo: Rest fragen
