### ISSUE TITLE
Empfang & Infodesk geplant

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#28]
- [x] Material Infodesk (inkl. Technik)
- [x] Poster, Flyer, QR-Codes etc
- [x] Bedarf externe Kräfte
- [x] Unterstützung zu Spitzenzeiten aus dem Team
- [x] Rolle Infodesk beschreiben

**Comment by sketchit4u** [comment]
### Rolle des Infodesk: (Vor Ort / Online)

Ein Infodesk spielt eine zentrale Rolle bei Veranstaltungen und übernimmt eine Vielzahl von Aufgaben, um den reibungslosen Ablauf zu unterstützen und den Teilnehmern eine angenehme Erfahrung zu bieten. Hier sind einige der wichtigsten Aufgaben, die ein Infodesk typischerweise übernimmt:

**Vor Ort:**
- First Level Support vor Ort
- Gate Keeper für den Event

**Online:** 
- First Level Support online
- Gate Keeper für den Event

### Planung der externen Kräfte
Als Gate Keeper brauchen wir mindestens eine ständige Besetzung des Infodesk vor Ort. Für die morgendlichen Spitzenzeiten  wären zwei Personen hilfreich. Falls wir studentische Hilfskräfte aus dem Bereich KM oder Lernen mit Freitickets gewinnen könnten, dann wäre ich für 3 Personen, die die Aufgabe Gate Keeper unter sich absprechen.

### Material für das Infodesk

- [ ] Info Plakate
- [ ] Tape & Schere
- [ ] Goodies
- [ ] Anmeldebogen für nicht registrierte Teilnehmer
- [ ] aktueller Zeitplan / Schichtplan
- [ ] Kontaktliste der Funktionsträger (Raumbuddies, Infodesk, etc)
- [ ] Handys mit Software zum registrieren
- [ ] Tablets mit Software zum registrieren
- [ ] PC mit Discord und Teams
- [ ] Papier und Stift für Logbucheinträge
- [ ] Sticky Notes


### Meeting des Infodesk der internen & externen Supporter
	
- [ ] Video der vergangenen Events teilen
- [ ] Anmeldebogen für nicht registrierte Teilnehmer liegt vor
- [ ] Zeitplan liegt vor
- [ ] Zeitplan und Verfügbarkeit sind abgestimmt
- [ ] 	Aufgabenliste ist besprochen
- [ ] 	Das Infodesk ist in der Registrierungssoftware eingerichtet
- [ ] 	Das Infodesk ist mit der Bedienung der Software vertraut

### Kurz vor dem Event:

- [ ] 	Briefing des kompletten Info Desk und Einstimmung in den Tag
- [ ] Orientierung und gemeinsamer Rundgang 
- [ ] 	Weg zum Eingang des Events tapen 
- [ ] 	Aufhängen der Plakate im Eingangsbereich
- [ ] 	Goodies auslegen und ggf. nachlegen
- [ ] 	Willkommenstisch je nach Wetter positionieren
- [ ] 	Software zum Registrieren Checken

### Beim Start des Events:
**Begrüßung der Teilnehmer:** Der erste Kontakt und ein freundlicher Empfang sind entscheidend für den ersten Eindruck der Veranstaltung.
**Registrierung und Check-In:** Erfassung der Anwesenheit, Ausgabe von Namensschildern, Teilnehmerunterlagen, Essensgutscheinen und Goodie.

- [ ] - 		 Nicht registrierte Besucher auf die Kosten zum Besuch des Events hinweisen.
- [ ] 				Zur Registrierung und Bezahlung Simon informieren

**Informationsservice:** Bereitstellung von Informationen zum Veranstaltungsprogramm, Zeitplan, Raumplan und allgemeinen Fragen.
	Das Infodesk verweist 
		
- [ ] auf die Plakate mit den Informationen zum Event
- [ ] 	Ort für Koffer und Reisetaschen hin

**Wegweiser:** Hilfe bei der Orientierung innerhalb der Veranstaltungsorte, Hinweise zu Sitzungsräumen und anderen wichtigen Orten.
**Unterstützung bei technischen Fragen:** Hilfe bei WLAN-Zugang, App-Nutzung oder anderen technischen Anliegen der Teilnehmer.
	**Verwaltung von Fundgegenständen:** Annahme und Aufbewahrung von verlorenen Gegenständen und deren Rückgabe an die Besitzer.
	**Notfallkontakt:** Erste Anlaufstelle bei Notfällen oder unvorhergesehenen Ereignissen, um schnelle Hilfe zu leisten.
		Hat eine Kontaktliste für Raum Buddies, …
		Logfile über Besonderheiten aufschreiben
		
### Nach dem Event:
	

- [ ] Plakate und Tapes abnehmen
- [ ] 	Goodies wieder verpacken
- [ ] 	Tische zurückräumen
- [ ] 	Logfile / Retrospektive mit Organisator teilen

Es ist wichtig, dass das Personal am Infodesk gut informiert, freundlich und hilfsbereit ist, um einen positiven und professionellen Eindruck zu hinterlassen. Die genauen Aufgaben können je nach Art und Größe der Veranstaltung variieren, aber diese Liste bietet einen guten Ausgangspunkt für die Planung eines effektiven Infodesks.
