### ISSUE TITLE
Programm erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#3]
- Version 1 bis 01.06. (mit Impulsen und 50% der Barcamp Sessions, Rest mit Pitch vor Ort)
- Version 2 bis 26.06. (mit Lightning Talks->Erfahrungsberichte aus dem kimooc24)

Impulsspeaker:
- lernOS State of the Union (Simon)
- Abstage: Prof. Katharina Zweig "Wie reden wir über/mit KI?" -> abgesagt
- Angefragt: Prof. Karsten Wendland "Selbstbewusste KI" -> abgesagt -> drei Alternativen empfohlen -> kontaktiert
- Zugesagt: Florian und Markus von Teaming with AI -> Markus kann, vor Ort
- AI & Ethik/Gesellschaft (Kontakt von Gabriele?)
- Dame Human Magazin, Corporate Digital Responsibility (Kontakte von Sabrina)

**Comment by dieSabrina** [comment]
@simondueckert von der https://cdr-initiative.de bekommen wir am 13.05. (wg.Urlaub)  die Rückmeldung,ob der wissenschaftliche Berater der Initiative Alexander Brink uns den erbetenen Impuls gibt. Also noch ein bisschen Daumen drücken, hörte sich aber von der Geschäftsleiterin gut an.

Ferner bin ich noch Kenza Ait Si Abbou in Kontakt dazu.

**Comment by simondueckert** [comment]
Miriam Meckel (Podcast) anfragen

**Comment by Nici-suedbaden** [comment]
kann ich eigentlich noch irgendwie unterstützen? irgendwelche Session einpflegen, Infos anlegen o.ä.?

**Comment by dieSabrina** [comment]
Kann auch gerne wenn es noch etwas gibt
