### ISSUE TITLE
Kommunikation und Infoseiten betreuen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#31]
Dazu gehören Linkedin-/Mastodon-Posts und die Redaktion der Infoseiten auf https://loscon.lernos.org

**Comment by Sandra-Richter** [comment]
Vermerk: Werbung/Posts loscon24 erst nach dem 15.05.

Mastodon: 
loscon@cogneon.io

sr -Sandra
oe- Oliver Ewinger

**Social Media Plan loscon24:** - Oliver, trag hier ein, wann & was & wo du posten möchtest

- [ ] 23.05.2024 Nachhaltigkeit und Mobilität (sr)
- [ ] 03.06.2024 noch 1 Monat bis zur loscon (Insights Orga) (sr)
- [ ] 05.06.2024 CfP bzw. Programm-Version 1 loscon (sr)
- [ ] 07.06. Orga-Team loscon (sr)
- [ ] ab 11.06. Sessions vorstellen (und ggf. zugehörige Leitfäden)
- [ ] Merch
- [ ] 24.06. Nächste Woche #loscon24 - wer ist in Nürnberg dabei?

**Comment by simondueckert** [comment]
Ich mache die nächsten Tage mal eine Bestandsaufnahme Infoseiten und liste hier die größten "Baustellen".

**Comment by Sandra-Richter** [comment]
@simondueckert Wie ist die Schriftart für die loscon? Ich finde das hier nirgends.

**Comment by simondueckert** [comment]
Hier: https://loscon.lernos.org/de/design/
________________________________
Von: Sandra-Richter ***@***.***>
Gesendet: Wednesday, May 22, 2024 11:56:01 AM
An: cogneon/loscon24 ***@***.***>
Cc: Simon Dückert ***@***.***>; Mention ***@***.***>
Betreff: Re: [cogneon/loscon24] Kommunikation und Infoseiten betreuen (Issue #31)


@simondueckert<https://github.com/simondueckert> Wie ist die Schriftart für die loscon? Ich finde das hier nirgends.

**Comment by Sandra-Richter** [comment]
Das war zu einfach. ;)

**Comment by Sandra-Richter** [comment]
Ich brauch auch die "normale" Schrift. Nicht nur die Überschrift. Da nimmst du ja bestimmt immer die gleiche, oder? Würde ich mir mal abspeichern in CANVA.

**Comment by simondueckert** [comment]
Ja, lernOS Standard-Schrift ist "open sans"
________________________________
Von: Sandra-Richter ***@***.***>
Gesendet: Wednesday, May 22, 2024 12:03:36 PM
An: cogneon/loscon24 ***@***.***>
Cc: Simon Dückert ***@***.***>; Mention ***@***.***>
Betreff: Re: [cogneon/loscon24] Kommunikation und Infoseiten betreuen (Issue #31)


Ich brauch auch die "normale" Schrift. Nicht nur die Überschrift. Da nimmst du ja bestimmt immer die gleiche, oder? Würde ich mir mal abspeichern in CANVA.
