### ISSUE TITLE
Merch und Drucksachen bestellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#32]
S.a. #19 

- [x] Sticker (Stickermule, klein)
- [x] Lanyards (hochwertig, wiederverwendbar, jährlich erweiterbar) -> bei Wir machen Druck bestellt, Lieferung 28.5.
- [x] Buttons, Klammern, Nieten etc. für Lanyard (auch für alte loscons)
- [x] Stifte? -> Simon macht Bestandsaufnahme -> wie viel ist noch da?
- [x] Becher? -> Simon macht Bestandsaufnahme -> wie viel ist noch da?
- [x] lernOS KI Leitfäden (300, auch für Versand)
- [x] Merch Shop anlegen -> Logo wg. Copyright-Verletzung abgelehnt, Alternative?
- [x] Badges (zum Aufbügeln, Bügelstation?) -> Anfrage an https://www.aufnaeher.de/gestickte-aufnaeher/ geschickt -> Lieeferzeit wäre zu lange gewesen
- [x] Poster (Simon macht Vorlage) -> keine Poster, wir machen DIN A4 Ausdrucke
- [x] Ergebnisgrafik loscon23 als Plane

**Comment by simondueckert** [comment]
Idee: Foto Booth

**Comment by simondueckert** [comment]
Die Sticker (rund, 50mm Durchmesser) sind bei Stickermul bestellt. Voraussichtliches Lieferdatum 9.5.

**Comment by dieSabrina** [comment]
Habe bei Trigema https://www.trigema-business.de/veredelungen/ wegen der Stickerei-Patches angefragt, aber sie schreiben _"Leider können wir nur Direkteinstickungen anbieten. Für die Anfertigung von Patches benötigt man Schneidmaschinen die den Patch dann ausschneiden, die wir leider nicht im Maschinenpark haben."_
