### ISSUE TITLE
Learning Circles organisieren

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#35]
Wie ist Übergang von MOOC zu loscon? Wo bekommen die Learning Circles einen Ort für den Austausch (vor Ort, Online, Discord?)

**Comment by Sandra-Richter** [comment]
Gute Frage! Sind ja auch nicht alle Circle komplett bei der loscon dabei.
Tatsächlich wäre vielleicht in dem Falle eine Neumischung für die loscon denkbar - so kommen nochmal neue Perspektiven rein.
Vielleicht könnten wir dann wieder mit Nummern/Bildchen/Herr-der-Ringe-Namen hantieren und so zufällige Gruppen zusammenführen, die bei der loscon an Tag 1 erst einmal 25min Zeit für hybriden Austausch bekommen via Videokanal in Discord. Gern auch mit einer Frage, die uns wichtig ist, damit sie etwas haben, an dem sie sich langhangeln können, falls sie nicht so extrovertiert sind. Diese Phase mit der Circlebildung im letzten Jahr fühlte sich zwar erst hektisch an, aber als sich alle gefunden hatten, habe ich viele fröhliche Gesichter gesehen.

**Comment by simondueckert** [comment]
Über den MOOC und die Vernetzungsaktion im Programm.
