### ISSUE TITLE
Details mit Veranstaltungsmanagement Burg klären

### ISSUE THREAD

**Issue by simondueckert** [cogneon/loscon24#42]
- [ ] Anzahl Teilnehmer: 120 (plusminus x)
- [ ] Aufbau Montag 14-18 Uhr
- [ ] Anfangs-/Endzeit Veranstaltung (Schlüssel, Telefon Ansprechpartner?)
- [ ] Catering von Burg
   - [ ] Getränke nach Verbrauch (Kaffee, Kaltgetränke, Wein/Bier Abends)
   - [ ] Tag 1 Mittag (hier bräuchten wir Voucher zum ausgeben, ca. 50)
   - [ ] Tag 1 Nachmittag
   - [ ] Tag 1 Abend (Metzgerei Meier liefern bis 18h an)
   - [ ] Tag 2 Vormittag
   - [ ] Tag 2 Mittag (Voucher für alle, Abrechnung nach Verbrauch?)
   - [ ] Tag 2 Nachmittag
- [ ] Bestuhlung Eppeleinsaal (Reihen senkrecht zur Bühne, ein runder Tisch hinten)
- [ ] Ausstattung Eppeleinsaal (Bühne, Beamer, FOH hinten, Anschluss PA hinten, XLR?)
- [ ] Ausstattung Seminarräume (Beamer, Leinwand)
- [ ] Podcast-Tisch (runder Tisch Foyer 1. Stock möglich?)
- [ ] Netzwerk/WiFi (SSID, Passwort)
- [ ] Reinigung (Hochzeit, Konfetti, Problem?)

**Comment by Sandra-Richter** [comment]
Im letzten Jahr sind die Kühlschränke irgendwann ausgestellt worden. Es wäre wundervoll, wenn das in diesem Jahr nicht so wäre. ;)

**Comment by Sandra-Richter** [comment]
Ich hatte ja mal die Idee, dass wir oben die "Bücherecke" aufbauen. Da ist es hell und freundlich. Sind dort die Sofas immer da oder musst du die extra bestellen? Ein Tisch oder Regal wäre ja dann dort auch nicht schlecht. 
Als Raum auch im Programm angeben? "Bibliothek von Minas Tirith" für die Nerds. ;)

**Comment by Sandra-Richter** [comment]
Vielleicht noch ein zusätzlicher Tisch für Ablage des schmutzigen Geschirrs.
